import Config

# Configure your database
config :buttonlog, ButtonLog.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 15442,
  database: "buttonlog_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :buttonlog, ButtonLogWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 14015, protocol_options: [max_header_name_length: 128, max_header_value_length: 16_384, max_headers: 200]],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Kh7LIE0FWdaQ/ThYYCasCt7AUPeIPkfgOp0oPWAfUH7ig2y0ukEFTMIjofcXolgh"

# OAuth Configuration for Development
config :ueberauth, Ueberauth,
  providers: [
    google: {Ueberauth.Strategy.Google, [
      client_id: System.get_env("GOOGLE_CLIENT_ID") || "your-google-client-id-here",
      client_secret: System.get_env("GOOGLE_CLIENT_SECRET") || "your-google-client-secret-here",
      redirect_uri: System.get_env("GOOGLE_REDIRECT_URI") || "http://localhost:14015/auth/google/callback"
    ]}
  ]

# Debug OAuth configuration
IO.puts "=== OAUTH DEBUG CONFIGURATION ==="
IO.puts "GOOGLE_CLIENT_ID: #{System.get_env("GOOGLE_CLIENT_ID") || "NOT SET"}"
IO.puts "GOOGLE_CLIENT_SECRET: #{System.get_env("GOOGLE_CLIENT_SECRET") || "NOT SET"}"
IO.puts "GOOGLE_REDIRECT_URI: #{System.get_env("GOOGLE_REDIRECT_URI") || "NOT SET"}"
IO.puts "=================================="

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :buttonlog, ButtonLogWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/buttonlog_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :buttonlog, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
