import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :buttonlog, ButtonLogWeb.Endpoint,
  url: [host: "your-domain.com", port: 443, scheme: "https"],
  http: [
    ip: {0, 0, 0, 0, 0, 0, 0, 0},
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to your endpoint configuration:
#
#     config :buttonlog, ButtonLogWeb.Endpoint,
#       https: [
#         ...,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SSL_KEYFILE"),
#         certfile: System.get_env("SSL_CERTFILE")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This ensures old browsers
# and clients are unable to connect to newer Phoenix applications.
# For more information, see https://www.owasp.org/index.php/SSL/TLS_Implementation_Cheat_Sheet#Rule_-_Only_Support_Strong_Encryption_Ciphers
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :buttonlog, ButtonLogWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Database
#
# You can configure the database connection pool in production
# by setting the `pool_size` value. This value should be set
# to the number of database connections you want to maintain.
# For more information, see:
# https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.html#module-connection-pool-configuration
#
config :buttonlog, ButtonLog.Repo,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

# Do not print debug messages in production
config :logger, level: :info

# Runtime configuration
config :buttonlog, :env, :prod
